### ISSUE TITLE
The README doesn't link back to the blog post

### ISSUE THREAD

**Issue by beatcracker** [CookiePLMonster/SilentPatchME#2]
In fact, none of the other patches do! It's a shame, since people arriving here from their GitHub feed are missing all the the fun. Please consider putting link to the [accompanying article](https://cookieplmonster.github.io/2020/07/19/silentpatch-mass-effect/) in this repo README (and hopefully others).

**Comment by CookiePLMonster** [comment]
It's a valid idea! I think I might add a "Related reads" to the readmes and encapsulate it there indeed. Might be a good idea to do something same on the blog, too.

**Comment by CookiePLMonster** [comment]
Added a link to README and also set the repository URL to the appropriate post. Should be enough!
