### ISSUE TITLE
Patch breaks enemy and companion AI during Virmire mission

### ISSUE THREAD

**Issue by JensDA** [CookiePLMonster/SilentPatchME#4]
During the Virmire assault mission, if the `d3dx9_31.dll` is in the Binaries directory, there is a point where enemies stop attacking (but are still moving) and the companions are getting stuck and don't get reset when the player moves on.
Progression into the base is not possible, as the doors are unable to be opened.
I have also noticed, that the UI says `Repairing` instead of `Fatigued` after sprinting.

I have confirmed that simply removing the SilentPatch DLL from Binaries fixes this issue.

[Talinn00_AutoSave.zip](https://github.com/CookiePLMonster/SilentPatchME/files/5350731/Talinn00_AutoSave.zip)

**Comment by adolfintel** [comment]
I can confirm this, but doors worked for me.

The Repairing/Fatigued is an ME1 bug, it happens if you get fatigued after repairing the mako, it's not caused by this patch.

**Comment by riverar** [comment]
Can reproduce using the attached .sav on Threadripper 1950X.

![](https://user-images.githubusercontent.com/475132/98448081-87e9b100-20de-11eb-9c1f-2bd8716179a1.gif)
*Enemy does not attack player and eventually just vanishes, companion taking a nap*

![me2](https://user-images.githubusercontent.com/475132/98448155-05152600-20df-11eb-9702-45b1d9b84fcb.gif)
*Enemy follows player but does not attack, companion taking a nap*

**Comment by mirh** [comment]
How in the heaven could AI be affected by graphics?
(also, could this help with #3?)
